export const siteConfig = {
  name: 'Intelsecsul - Segurança Eletrônica',
  shortName: 'Intelsecsul',
  tagline: 'Segurança Eletrônica e Tecnologia em Curitiba e Região Metropolitana',
  domain: 'https://intelsecsul.com.br',
  phoneDisplay: '(41) 99844-8409',
  phoneRaw: '5541998448409',
  phoneSchema: '+5541998448409',
  phoneTel: 'tel:+5541998448409',
  email: 'contato@intelsecsul.com.br',
  googleReviewsUrl: 'https://share.google/dNAmcesFz6QV1vroW',
  googleRating: '5.0',
  googleReviewCount: '15',
  cityBase: 'Curitiba - PR',
  hours: 'Segunda a Sexta: 08:00 às 18:00 | Emergências 24h',
  address: {
    street: 'Curitiba e Região Metropolitana',
    city: 'Curitiba',
    state: 'PR',
    country: 'BR',
  },
  citiesServed: [
    'Curitiba',
    'Pinhais',
    'São José dos Pinhais',
    'Araucária',
    'Almirante Tamandaré',
    'Colombo',
    'Campo Largo',
    'Fazenda Rio Grande',
    'Campo Magro',
    'Quatro Barras',
    'Campina Grande do Sul',
  ],
};
